---
-- #%L
-- i2b2 Export Service
-- %%
-- Copyright (C) 2013 Emory University
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
alter table column_configs drop constraint FK8CF9A98899BE0907;
alter table column_configs drop constraint FK8CF9A9887A6ACF61;
drop table column_configs if exists;
drop table i2b2_concepts if exists;
drop table output_configs if exists;
create table column_configs (column_config_id bigint generated by default as identity, aggregation integer, column_name varchar(255) not null, column_order integer not null, display_format integer not null, how_many integer, include_time_range boolean, include_units boolean, i2b2_concept_id bigint, config_id bigint, primary key (column_config_id));
create table i2b2_concepts (concept_id bigint generated by default as identity, c_columnname varchar(255), c_dimcode varchar(255) not null, c_displayname varchar(255), c_children varchar(255), i2b2_key varchar(255) not null, c_icd9 varchar(255), c_synonym_cd varchar(255) not null, c_hlevel integer not null, c_name varchar(255), c_operator varchar(255), c_tablename varchar(255) not null, c_tooltip varchar(255), c_xml_orig CLOB, primary key (concept_id));
create table output_configs (config_id bigint generated by default as identity, missing_value varchar(255), config_name varchar(255), quote_char varchar(1), row_dimension integer not null, separator varchar(1), username varchar(255) not null, whitespace_replacement varchar(255), primary key (config_id), unique (username, config_name));
alter table column_configs add constraint FK8CF9A98899BE0907 foreign key (config_id) references output_configs;
alter table column_configs add constraint FK8CF9A9887A6ACF61 foreign key (i2b2_concept_id) references i2b2_concepts;
